version: "2.1"

services:
  db:
    image: "linz-gazetteer-db:${PGSQL_VERSION:-8.4}--${PGIS_VERSION:-1.5.8}"
    build:
      context: src/sql/
      args:
        - PGSQL_VERSION=${PGSQL_VERSION:-8.4}
        - PGIS_VERSION=${PGIS_VERSION:-1.5.8}
    ports:
      - "5432"
    volumes:
      - ./src/sql/test/:/sql/test/
      # This helps ensure that the data persists even if the Postgres container is deleted.
      #- ./data:/var/lib/postgresql/data
    #environment:
      #POSTGRES_DB: github_ci_test
      #POSTGRES_USER: postgres
      #POSTGRES_PASSWORD: postgres

  qgis:
    image: "linz-gazetteer-qgis:${QGIS_TAG:-3.10}"
    build:
      context: src/NZGBplugin
      args:
        - UPSTREAM_TAG=${QGIS_TAG:-3.10}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./src/NZGBplugin:/root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/NZGBplugin
      - ./.docker/qgis/scripts:/scripts
    depends_on:
      - db
    command: /scripts/docker-entry.sh
    environment:
      PGHOST: db
      PGPASSWORD: gazdba
      PGUSER: gazdba
      PGDATABASE: gazetteer
