FROM kartoza/qgis-desktop:2.14

ADD .  /root/.qgis2/python/plugins/NZGBplugin

#RUN qgis_setup.sh NZGBplugin

#RUN ln -fs /tests_directory /root/.local/share/QGIS/QGIS3/profiles/default/python/plugins

