#!/bin/sh

CONFIGFILE=/root/.local/share/QGIS/QGIS3/profiles/default/QGIS/QGIS3.ini

# Set NZGBplugin as enabled in config
mkdir -p `dirname ${CONFIGFILE}`
echo '[PythonPlugins]' >  ${CONFIGFILE}
echo 'NZGBplugin=true' >> ${CONFIGFILE}

# Disable newsfeed
cat <<EOF >> ${CONFIGFILE}
[core]
NewsFeed\httpsfeedqgisorg\disabled=true
EOF

# Do not check for new QGIS versions at startup
cat <<EOF >> ${CONFIGFILE}
[qgis]
checkVersion=false
EOF
