#!/bin/sh

CONFIGFILE=/root/.local/share/QGIS/QGIS3/profiles/default/QGIS/QGIS3.ini

# Set NZGBplugin as enabled in config
mkdir -p `dirname ${CONFIGFILE}`
echo '[PythonPlugins]' >  ${CONFIGFILE}
echo 'NZGBplugin=true' >> ${CONFIGFILE}

# Do not show startup tips in QGIS..
#echo '[Qgis]' >> ${CONFIGFILE}
#echo 'showTips214=false' >> ${CONFIGFILE}
