name: Plugin test

on: [push, pull_request]

jobs:

  test:

    runs-on: ubuntu-18.04
    env:
      DOCKER_COMPOSE_VERSION: 1.7.1
    steps:
    - uses: actions/checkout@v1
    - name: Start docker containers for plugin test
      run: |
        cd src/NZGBplugin
        docker-compose up -d
    - name: Setup Plugin
      run: |
        cd src/NZGBplugin
        docker-compose exec -T qgis-testing-environment sh -c "qgis_setup.sh NZGBplugin"
        docker-compose exec -T qgis-testing-environment sh -c "ln -fs /tests_directory /root/.local/share/QGIS/QGIS3/profiles/default/python/plugins"
